### ISSUE TITLE
Could you update this project to Processing3? 

### ISSUE THREAD

**Issue by q2dg** [firmata/processing#5]
Thanks!!

**Comment by damellis** [comment]
Hmm... does it not work there? What problem do you see?

**Comment by q2dg** [comment]
Thanks for your intereset.
In fact, I haven't tried...Maybe anything fails, but I wanted to be sure this repository is up to date. My intention only was pointing up on this necessary maintenance: I've just seen last commit was from two years ago...
Thanks!

**Comment by damellis** [comment]
I just did a basic check with Processing 3 and it seems to work, so I'm closing this. Let me know if you run into any problems. Thanks!
